protected/controllers/CrepairController.php
<?php

class CrepairController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = '//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
//			'postOnly + delete', // we only allow deletion via POST request
		);

	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('index', 'history', 'activeparts', 'Create', 'historyparts', 'newrepair', 'newactiveparts'),
				'users' => array('@'),
			),
			array('allow',
				'actions' =>array('support'),
				'roles' => array(User::ROLE_MODERATOR),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Repair;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Repair'])) {
			$model->attributes = $_POST['Repair'];
			if ($model->save()) {
				Yii::app()->user->setFlash('info', 'New repair was added successfully');
				$this->redirect(array('view', 'id' => $model->repair_id));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($mpp = 10)
	{
		if(!Yii::app()->user->checkAccess(User::ROLE_ADMIN)&&!Yii::app()->user->checkAccess(User::ROLE_CUSTOMER)){
			$this->redirect(Yii::app()->createAbsoluteUrl('crepair/support'));
		}

		$model = new Repair('search');
		$model->unsetAttributes(); // clear any default values

		if (isset($_GET['inpSearch'])) {
			$model->mixedSearch = $_GET['inpSearch'];
		}
		if (isset($_GET['Repair']))
			$model->attributes = $_GET['Repair'];
		if (Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
			$model->activeRepairs();
		else $model->ownRepairs()->activeRepairs();


		// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
		$dataProvider = new CActiveDataProvider($model, array(
			'Pagination' => array(
				'PageSize' => $mpp,
			),
		));

		$this->render('index', array(
			'model' => $model, 'dp' => $dataProvider
		));
	}


	public function actionSupport($mpp = 10)
	{
		$model = new Repair('search');
		$model->unsetAttributes(); // clear any default values
		$model->MyRepairsAndFreeRepairs(Yii::app()->user->id);
		if (isset($_GET['inpSearch'])) {
			$model->mixedSearch = $_GET['inpSearch'];
		}
		if (isset($_GET['Repair']))
			$model->attributes = $_GET['Repair'];


		// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
		$dataProvider = new CActiveDataProvider($model, array(
			'Pagination' => array(
				'PageSize' => $mpp,
			),
		));

		$this->render('index', array(
			'model' => $model
		));
	}


	public function actionNewrepair($mpp = 10)
	{
		$id = -1;
		(Yii::app()->user->checkAccess(User::ROLE_MODERATOR)) ? $id = -1 : $id = Yii::app()->user->id;
		$notif = Message::model()->findAllByAttributes(array('to_id' => $id, 'new' => Message::MESSAGE_NEW, 'type' => array(Message::TYPE_NEW_REPAIR, Message::TYPE_REPAIR_STATUS_CHANGE)));

		if ($notif) {
			$ids = Array();

			foreach ($notif as $n) {
				array_push($ids, $n->repair_id);
				$n->new = Message::MESSAGE_OLD;
				$n->save();
			}
			$model = new Repair('search');
			$model->unsetAttributes(); // clear any default values
			$model->byIds($ids);


			// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
			$dataProvider = new CActiveDataProvider($model, array(
				'Pagination' => array(
					'PageSize' => $mpp,
				),
			));


			$this->render('index', array(
				'model' => $model, 'dp' => $dataProvider,
			));


		} else {
			Yii::app()->user->setFlash('Success', 'No new notifications');
			$this->redirect(Yii::app()->createAbsoluteUrl('crepair'));
		}
	}

	public function actionNewactiveparts()
	{
		$id = -1;
		(Yii::app()->user->checkAccess(User::ROLE_MODERATOR)) ? $id = -1 : $id = Yii::app()->user->id;
		$notif = Message::model()->findAllByAttributes(array('to_id' => $id, 'new' => Message::MESSAGE_NEW,
			'type' => array(Message::TYPE_NEW_PARTS, Message::TYPE_REPAIR_STATUS_CHANGE)));

		if ($notif) {
			$ids = Array();

			foreach ($notif as $n) {
				array_push($ids, $n->repair_id);
				$n->new = Message::MESSAGE_OLD;
				$n->save();
			}
			$model = new Repair('search');
			$model->unsetAttributes(); // clear any default values
			$model->byIds($ids);
			$this->render('index', array(
				'model' => $model,
			));
		} else {
			Yii::app()->user->setFlash('Success', 'No new notifications');
			$this->redirect(Yii::app()->createAbsoluteUrl('crepair'));
		}
	}

	public function actionHistory($mpp = 10)
	{
		$model = new Repair('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Repair']))
			$model->attributes = $_GET['Repair'];
		if (Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
			$model->historyRepairs();
		else $model->ownRepairs()->historyRepairs();

		// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
		$dataProvider = new CActiveDataProvider($model, array(
			'Pagination' => array(
				'PageSize' => $mpp,
			),
		));


		$this->render('index', array(
			'model' => $model, 'dp' => $dataProvider,
		));
	}

	public function actionActiveParts($mpp = 10)
	{
		$model = new Repair('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Repair']))
			$model->attributes = $_GET['Repair'];
		if (isset($_GET['inpSearch'])) {
			$model->ms = $_GET['inpSearch'];
		}
		if (Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
			$model->activeParts();
		else $model->ownParts()->activeParts();


		// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
		$dataProvider = new CActiveDataProvider($model, array(
			'Pagination' => array(
				'PageSize' => $mpp,
			),
		));


		$this->render('parts', array(
			'model' => $model, 'dp' => $dataProvider
		));
	}

	public function actionHistoryParts($mpp = 10)
	{
		$model = new Repair('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Repair']))
			$model->attributes = $_GET['Repair'];
		if (Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
			$model->historyParts();
		else $model->ownParts()->historyParts();


		// если че удалить эту хуйню и во вьюшке в дата провайдере вернуть модель-серч
		$dataProvider = new CActiveDataProvider($model, array(
			'Pagination' => array(
				'PageSize' => $mpp,
			),
		));


		$this->render('parts', array(
			'model' => $model, 'dp' => $dataProvider
		));
	}

	/**
	 * Manages all models.
	 */


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Repair the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model = Repair::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Repair $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'repair-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php
class UserController extends Controller
{
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','registration','Approveme'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('Profile','editUser','Logout'),
                'users'=>array('@'),
            ),

        );
    }

    public function actionIndex()
    {
        $model = new User('login');
        if(Yii::app()->user->isGuest)
        {
            if (Yii::app()->request->getPost('User'))
            {
                $model->attributes = Yii::app()->request->getPost('User');
                if($model->login())
                {
                    $this->redirect(Yii::app()->createAbsoluteUrl('user/profile'));
                }
            }
        $this->render('index',array('model'=>$model));
        }
        else $this->redirect(Yii::app()->createAbsoluteUrl(Yii::app()->controller->id.'/profile'));
    }




    public function actionRegistration()
    {
        $model = new User('registration');
        if (Yii::app()->request->getPost('User'))
        {
			$model->attributes = Yii::app()->request->getPost('User');

        if($model->regUser())
        {
            $this->redirect(Yii::app()->homeUrl);
        }
        }
        $this->render('registration',array('model'=>$model));
    }

    public function actionProfile($id = null){
        $model = new User('profile');
        $model = $model->getUserData($id);
        $this->render('profile',array('model'=>$model,'id'=>$id));
    }

    public function actionEdit($id = null){
        $model = User::model()->getUserData($id);
        $model->setScenario('editUser');

        if(Yii::app()->request->getPost('User'))
        {
            $model->attributes = Yii::app()->request->getPost('User');

                if($model->save())
            $this->redirect(Yii::app()->createAbsoluteUrl(Yii::app()->controller->id).'/profile/'.$model->id);
        }
        $this->render('profile',array('model'=>$model,'id'=>$id));
    }

	public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->createAbsoluteUrl('user/index'));
    }


    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

	public function actionApproveme($url)
	{
		//YXByb3ZlX2VtYWlsOjE6YmFvam5zZ2VAMTBtYWlsLm9yZzpiYW9qbnNnZUAxMG1haWwub3JnOmNmYWRhOmFkc2FkYQ
		/** @var User $model */
		$model = User::model();
		if($model->approveUrl($url)){
			Yii::app()->user->setFlash('success','You\'r approve your email. Now you can enter');
			$this->redirect(Yii::app()->createAbsoluteUrl('/'));
		}else{
			Yii::app()->user->setFlash('error','Something went wrong. please contact with admins');
			$this->redirect(Yii::app()->createAbsoluteUrl('/'));
		}
	}

}

protected/views/layouts/_menu.php
<?php

$user = Yii::app()->user;

function getItems()
{
	$user = Yii::app()->user;
	return array(
		array('label' => 'Home', 'url' => array('/site/index')),
		array('label' => 'Sign in', 'url' => array('/site/login'), 'visible' => $user->isGuest),
		array('label' => 'Sign up', 'url' => array('/site/registration'), 'visible' => $user->isGuest),
		array('label' => 'Logout (' . (!$user->isGuest ? Yii::app()->user->email : '') . ')', 'url' => array('/site/logout'), 'visible' => !$user->isGuest),
		array('label' => 'Edit users', 'url' => array('/user/index'), 'visible' => $user->checkAccess('editUser')),
		array('label' => 'Add post', 'url' => array('/post/add'), 'visible' => !$user->isGuest),
		array('label' => (($user->checkAccess('editPost')) ? 'All' : 'My') . ' posts', 'url' => array('/post/index/'), 'visible' => !($user->isGuest)),
		array('label' => 'Profile', 'url' => array('/profile/index'), 'visible' => !$user->isGuest),
	);
}

$this->widget('zii.widgets.CMenu', array(
	'items' => getItems(),
	'htmlOptions' => array('id' => 'top', 'class' => 'col-xs-12 text-right hidden-xs')
));


$this->widget('zii.widgets.CMenu', array(
	'items' => getItems(),
	'htmlOptions' => array('id' => 'top-xs', 'class' => 'col-xs-12 text-center visible-xs')
));

protected/views/layouts/header.php
<?
if(!Yii::app()->user->isGuest)
{

echo '<div class="col-lg-12 header" id="itisheader" align="center">';



	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR)){

	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>array(Message::TO_ADMINS_AND_MODERS,
			Yii::app()->user->id),
			'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)))
		{
			$amount = count(Message::model()->findAllByAttributes(array('to_id'=>array(Message::TO_ADMINS_AND_MODERS,Yii::app()->user->id),
				'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)));
			$class =  'header_button';
		}
		else $class = 'header_button';
	}
	else $class = 'header_button';
	$this->widget('bootstrap.widgets.TbButton', array(
		'label'=>'Messages',
		'url'=>Yii::app()->createAbsoluteUrl('messages/'),//'messages controller',
		'htmlOptions'=>array('class'=>$class)
	));
	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>array(Message::TO_ADMINS_AND_MODERS,
			Yii::app()->user->id),
			'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)))
		{
			$this->widget('bootstrap.widgets.TbButton', array(
				'label'=>$amount,
				'url'=>Yii::app()->createAbsoluteUrl('messages/'),//'repairs',
				'htmlOptions'=>array('class'=>'amount_header_button')
			));
		}
	}
	}
	/*******************4 users************************/


	if(!Yii::app()->user->checkAccess(User::ROLE_MODERATOR)&&!Yii::app()->user->checkAccess(User::ROLE_ADMIN)
		&&Yii::app()->user->checkAccess(User::ROLE_CUSTOMER)){


			if(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
				'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)))
			{
				$amount = count(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
					'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)));
			}
		$class =  'header_button';

		$this->widget('bootstrap.widgets.TbButton', array(
			'label'=>'Messages',
			'url'=>Yii::app()->createAbsoluteUrl('messages/'),//'messages controller',
			'htmlOptions'=>array('class'=>$class)
		));

			if(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
				'type' => array(Message::TYPE_MESSAGE),'new'=>Message::MESSAGE_NEW)))
			{
				$this->widget('bootstrap.widgets.TbButton', array(
					'label'=>$amount,
					'url'=>Yii::app()->createAbsoluteUrl('messages/?new=1'),//'repairs',
					'htmlOptions'=>array('class'=>'amount_header_button')
				));
			}

	}
/////////////////////////////////////////////////////


    if(Yii::app()->user->checkAccess(User::ROLE_ADMIN))
    {
        $this->widget('bootstrap.widgets.TbButton', array(
            'label' => 'Color palette',
            'url' => Yii::app()->createAbsoluteUrl('repairs/palette'),
            'htmlOptions' => array('class' => 'header_button')
        ));

        $this->widget('bootstrap.widgets.TbButton', array(
            'label' => 'Shipping Methods',
            'url' => Yii::app()->createAbsoluteUrl('sendmethod/'),
            'htmlOptions' => array('class' => 'header_button')
        ));
    }

if (Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
{

$this->widget('bootstrap.widgets.TbButton', array(
    'label' => 'Brands',
    'url' => Yii::app()->createAbsoluteUrl('brand/'), //'repairs',
    'htmlOptions' => array('class' => 'header_button')
));









	/**************************************************************************/




	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_USER),'new'=>Message::MESSAGE_NEW)))
		{
			$amount = count(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
				'type' => array(Message::TYPE_NEW_USER),'new'=>Message::MESSAGE_NEW)));
			$class =  'header_button';
		}
		else $class = 'header_button';
	}
	else $class = 'header_button';
	$this->widget('bootstrap.widgets.TbButton', array(
		'label'=>'User Management',
		'url'=>Yii::app()->createAbsoluteUrl('users'),//'repairs',
		'htmlOptions'=>array('class'=>$class)
	));
	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_USER),'new'=>Message::MESSAGE_NEW)))
		{
			$this->widget('bootstrap.widgets.TbButton', array(
				'label'=>$amount,
				'url'=>Yii::app()->createAbsoluteUrl('users/?User[active]=2'),//'repairs',
				'htmlOptions'=>array('class'=>'amount_header_button')
			));
		}
	}

/************************************************************/

}
if (Yii::app()->user->checkAccess(User::ROLE_CUSTOMER))
{

    $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Profile',
        'url' =>  Yii::app()->createAbsoluteUrl('/'),
        'htmlOptions' => array('class' => 'header_button')
    ));


    /////////////////////////// Checking for new repairs ////////////////////////////////////////////
    if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
    {
        if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_REPAIR,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
        {
            $amount = count(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
				'type' => array(Message::TYPE_NEW_REPAIR,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)));
            $class =  'header_button';
        }
        else $class = 'header_button';
    }
    else $class = 'header_button';
$this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Repairs',
    'url'=>Yii::app()->createAbsoluteUrl('crepair'),//'repairs',
    'htmlOptions'=>array('class'=>$class)
));
    if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
    {
        if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_REPAIR,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
        {
            $this->widget('bootstrap.widgets.TbButton', array(
                'label'=>$amount,
                'url'=>Yii::app()->createAbsoluteUrl('crepair/newrepair'),//'repairs',
                'htmlOptions'=>array('class'=>'amount_header_button')
            ));
        }
    }
/////////////////////////////////////////////////////////////////////////////////



    $this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'New Repair',
    'url'=>Yii::app()->createAbsoluteUrl('repairs/new'),
    'htmlOptions'=>array('class'=>'header_button')
));
    /////////////////////////// Checking for new Spare parts oreders ////////////////////////////////////////////

	if(Yii::app()->user->checkAccess(User::ROLE_CUSTOMER))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
			'type' => array(Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
		{
			$amount = count(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
				'type' => array(Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)));
			$class =  'header_button';
		}
		else $class = 'header_button';

	}

    if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
    {
        if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_PARTS,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
        {
            $amount = count(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
				'type' => array(Message::TYPE_NEW_PARTS,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)));
            $class =  'header_button';
        }
        else $class = 'header_button';

    }
    else $class = 'header_button';

    $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Spare Parts',
        'url' =>  Yii::app()->createAbsoluteUrl('/crepair/activeparts'),
        'htmlOptions' => array('class' => $class)
    ));
    if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR))
    {
        if(Message::model()->findAllByAttributes(array('to_id'=>Message::TO_ADMINS_AND_MODERS,
			'type' => array(Message::TYPE_NEW_PARTS,Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
        {
            $this->widget('bootstrap.widgets.TbButton', array(
                'label'=>$amount,
                'url'=>Yii::app()->createAbsoluteUrl('/crepair/newactiveparts'),//'repairs',
                'htmlOptions'=>array('class'=>'amount_header_button')
            ));
        }

    }

	if(Yii::app()->user->checkAccess(User::ROLE_CUSTOMER))
	{
		if(Message::model()->findAllByAttributes(array('to_id'=>Yii::app()->user->id,
			'type' => array(Message::TYPE_REPAIR_STATUS_CHANGE),'new'=>Message::MESSAGE_NEW)))
		{
			$this->widget('bootstrap.widgets.TbButton', array(
				'label'=>$amount,
				'url'=>Yii::app()->createAbsoluteUrl('/crepair/newactiveparts'),//'repairs',
				'htmlOptions'=>array('class'=>'amount_header_button')
			));
		}

	}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////


	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR)){
		if(Repair::model()->findAllByAttributes(array('support_id'=>Yii::app()->user->id))){

		}
	}




	//////////////////////////////////////////////////
    $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Logout',
        'url' => Yii::app()->createAbsoluteUrl('user/logout'),
        'htmlOptions' => array('class' => 'header_button')
    ));
}


    echo '</div>';
}

protected/views/layouts/main.php
<?php /* @var Controller $this */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="language" content="en"/>

	<?php
	Yii::app()->getClientScript()->registerCoreScript('jquery');

	$this->cs->registerCssFile(Yii::app()->request->baseUrl . '/css/bscomb.css');
	$this->cs->registerCssFile(Yii::app()->request->baseUrl . '/css/style.css');

	$this->cs->registerCssFile(Yii::app()->request->baseUrl . '/vendors/bootstrap/css/bootstrap.min.css');
	$this->cs->registerCssFile(Yii::app()->request->baseUrl . '/vendors/bootstrap/css/bootstrap-theme.css');
//	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/vendors/jquery/jquery-2.1.0.min.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/vendors/bootstrap/js/bootstrap.min.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/html2canvas.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/pdf.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/app.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/drop.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/growl.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/acp.js', CClientScript::POS_END);
	$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/vendors/colorpicker/js/colpick.js',
		CClientScript::POS_END);
	$this->cs->registerCssFile(Yii::app()->request->baseUrl . '/vendors/colorpicker/css/colpick.css');
	if(Yii::app()->user->checkAccess(User::ROLE_MODERATOR)){
		$this->cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/support.js', CClientScript::POS_END);
	}
	echo '<input type="hidden" id="controller_id" value="'.Yii::app()->controller->id.'"/>';
	echo '<input type="hidden" id="action_id" value="'.Yii::app()->controller->action->id.'"/>';
	if(Yii::app()->user->isGuest&&Yii::app()->controller->id!='user'){
		$this->redirect(Yii::app()->createAbsoluteUrl('/'));
	}
	?>

	<title><?= CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<? include_once('notifications.php') ?>


<div class="col-lg-12 main" align="center">
    <? if(!Yii::app()->user->isGuest){
        include_once('header.php');
    }
     ?>
	<div id="logo"></div>
<?= $content; ?>

	<input id="base_url" style="display:none;" value="<?=Yii::app()->createAbsoluteUrl('user/logout');?>"/>
</div>

</body>
</html>