protected/controllers/RepairsController.php
<?php

class RepairsController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
			//'postOnly + delete',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('new', 'details', 'deletecomment', 'editcomment', 'AddComment', 'NewPart', 'partsdetails'),
				'users' => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('palette', 'update','AddHiddenComment'),
				'roles' => array(User::ROLE_ADMIN, User::ROLE_MODERATOR),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	public function actionDetails($id)
	{
		$model = Repair::model()->with
			('client',
				'messages',
				'brand',
				'support', 'sendMethod')->findByAttributes(array('repair_id' => $id));
		if (!isset($model->sendMethod->name)) {
			$model->sendMethod = Sendmethod::model()->find();
		}
		if (isset($_POST['Repair']['warehouse_id']) && $model->warehouse_id !== $_POST['Repair']['warehouse_id'] && $model->warehouse_id !== null) {
			$warehouse = Warehouse::model()->findByAttributes(array('number' => $model->warehouse_id));
			if ($warehouse) {
				$warehouse->status = Warehouse::STATUS_EMPTY;
				$warehouse->save();
			}
		}
		if (Yii::app()->request->getPost('Repair')) {

//			die(var_dump(Yii::app()->request->getPost('Repair')));
			$model->attributes = Yii::app()->request->getPost('Repair');
			(!is_numeric($model->price)) ? $model->price = 0 : $model->price = $model->price;
			(!is_numeric($model->support_id)) ? $model->support_id = NULL : $model->support_id = $model->support_id;
			if ($model->save()) {

				if (isset($model->warehouse_id)) {
					$warehouse = Warehouse::model()->findByAttributes(array('number' => $model->warehouse_id));
					if ($warehouse) {
						$warehouse->status = Warehouse::STATUS_NOT_EMPTY;
						$warehouse->save();
					}
				}

				$mes = new Message();
				$mes->type = Message::TYPE_REPAIR_STATUS_CHANGE;
				if (Yii::app()->user->checkAccess(User::ROLE_CUSTOMER) && (!Yii::app()->user->checkAccess
							(User::ROLE_MODERATOR) && !Yii::app()->user->checkAccess(User::ROLE_ADMIN))
				) {
					$mes->from_id = Yii::app()->user->id;
					$mes->to_id = Message::TO_ADMINS_AND_MODERS;
				} else {
					$mes->from_id = Yii::app()->user->id;
					$mes->to_id = $model->client_id;
				}
				$mes->repair_id = $model->repair_id;
				$mes->new = Message::MESSAGE_NEW;
				$mes->message = 'Changed';
				$mes->save();

				Yii::app()->user->setFlash('success', 'All changes was added');
				$this->redirect(Yii::app()->createAbsoluteUrl('crepair/'));
			} else {
				die(var_dump($model->getErrors()));

			}
		}
		if ($model)
			$this->render('details', array('model' => $model));
		else {
			Yii::app()->user->setFlash('warning', 'Repair not found');
			$this->redirect(Yii::app()->createAbsoluteUrl('crepair/index'));
		}
	}

	public function actionPartsDetails($id)
	{
		$model = Repair::model()->with
			('client',
				'messages',
				'support')->findByAttributes(array('repair_id' => $id));
		if (Yii::app()->request->getPost('Repair')) {
			$model->attributes = Yii::app()->request->getPost('Repair');
			if ($model->save()) {
				$mes = new Message();
				$mes->type = Message::TYPE_REPAIR_STATUS_CHANGE;
				if (Yii::app()->user->checkAccess(User::ROLE_CUSTOMER) && (!Yii::app()->user->checkAccess
							(User::ROLE_MODERATOR) && !Yii::app()->user->checkAccess(User::ROLE_ADMIN))
				) {
					$mes->from_id = Yii::app()->user->id;
					$mes->to_id = Message::TO_ADMINS_AND_MODERS;
				} else {
					$mes->from_id = Yii::app()->user->id;
					$mes->to_id = $model->client_id;
				}
				$mes->repair_id = $model->repair_id;
				$mes->new = Message::MESSAGE_NEW;
				$mes->message = 'Changed';
				$mes->save();
				Yii::app()->user->setFlash('success', 'All changes was added');
				$this->redirect(Yii::app()->createAbsoluteUrl('crepair/activeparts/'));
			}
		}
		$this->render('partsdetails', array('model' => $model));
	}


	public function actionNew()
	{
		$model = new Repair('newrepair');
		if (Yii::app()->request->getPost('Repair')) {

			$model->attributes = Yii::app()->request->getPost('Repair');
			if (!isset($model->client_id)) {
				$model->client_id = Yii::app()->user->id;
			}
			if ($model->save()) {
				$notification = new Message();
				$notification->from_id = $model->client_id;
				$notification->repair_id = $model->repair_id;
				$notification->to_id = Message::TO_ADMINS_AND_MODERS;
				$notification->type = Message::TYPE_NEW_REPAIR;
				$notification->message = "New repair from " . $model->client->login;
				if ($notification->save()) {
					Yii::app()->user->setFlash('info', 'New repair was added successfully');
					$this->redirect(Yii::app()->createAbsoluteUrl('/repairs/details/' . $model->repair_id));
					return true;
				} else {
					$model->addError('Notification', 'Something went wrong, contact with support');
					$this->render('new', array('model' => $model));
					return false;
				}

				// form inputs are valid, do something here
				return true;
			}
		}
		$this->render('new', array('model' => $model));
	}

	public function actionNewPart()
	{
		$model = new Repair('newpart');
		if (Yii::app()->request->getPost('Repair')) {


			// NEVER USE $_POST[''] !!!
			// Use Yii::app()->request->getPost('')
			// Lesha would kill you for this :D

			$model->attributes = Yii::app()->request->getPost('Repair');
			$model->type = Repair::TYPE_PARTS;
			$attach = new Attachment();
			$attach->attachment = $model->attachment;

			if (!isset($model->client_id)) {
				$model->client_id = Yii::app()->user->id;
			}

			if ($model->save()) {
				$attach->part_id = $model->repair_id;
				$attach->save();
				$notification = new Message();
				$notification->from_id = $model->client_id;
				$notification->repair_id = $model->repair_id;
				$notification->to_id = Message::TO_ADMINS_AND_MODERS;
				$notification->type = Message::TYPE_NEW_PARTS;
				$notification->message = "new orders for parts from " . Yii::app()->user->login;
				if ($notification->save()) {
					Yii::app()->user->setFlash('info', 'New order for spare part was added successfully');
					$this->redirect(Yii::app()->createAbsoluteUrl('/repairs/partsdetails/' . $model->repair_id));
					return true;
				} else {
					$model->addError('Notification', 'Something went wrong, contact with support');
					$this->render('new', array('model' => $model));
					return false;
				}

				// form inputs are valid, do something here
				return true;
			}
		}
		$this->render('newpart', array('model' => $model));
	}

	public function actionPalette()
	{
		$model = new Colors('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Colors']))
			$model->attributes = $_GET['Colors'];

		$this->render('palette', array(
			'model' => $model,
		));
	}


	public function actionDeleteComment($id)
	{
		$model = Message::model()->findByPK($id);
		if ($model->delete()) {
			Yii::app()->user->setFlash('info', 'Comment was successfully deleted');
		}
		$this->redirect(Yii::app()->createAbsoluteUrl('/'));
	}

	public function actionEditComment($id)
	{
		$model = Message::model()->findByPK($id);
		if (Yii::app()->request->getPost('Message')) {
			$model->attributes = Yii::app()->request->getPost('Message');
			if ($model->save())
				Yii::app()->user->setFlash('info', 'Comment was updated successfully');
			$this->redirect(Yii::app()->createAbsoluteUrl('crepair'));
		}
		$this->render('editcomment', array('model' => $model, 'id' => $id));
	}

	public function actionAddComment($id)
	{
		/** @var Message $model */
		$model = new Message('add');
		if (Yii::app()->request->getPost('Message')) {
			$model->attributes = Yii::app()->request->getPost('Message');
			$model->repair_id = $id;
			$model->from_id = Yii::app()->user->id;
			if ($model->save()) {
				Yii::app()->user->setFlash('info', 'Your comment was added successfully');
				$this->redirect(Yii::app()->user->returnUrl);
				/** @var Repair $client */
				$client = Repair::model()->findByPk($id);
				$notif = new Message();

				if ($client->client_id == Yii::app()->user->id) {
					$notif->from_id = Yii::app()->user->id;
					$notif->to_id = Message::TO_ADMINS_AND_MODERS;
				} else {
					$notif->from_id = Yii::app()->user->id;
					$notif->to_id = $client->client_id;
				}

				$notif->type = Message::TYPE_NEW_COMMENT;
				$notif->new = Message::MESSAGE_NEW;
				$notif->save();
			} else {
				die(var_dump('some_error'));
			}
		}
		$this->render('editcomment', array('model' => $model, 'id' => $id));

	}

    public function actionAddHiddenComment($id)
    {
        /** @var Message $model */
        $model = new Message('add');
        $model->hidden = 1;
        if (Yii::app()->request->getPost('Message')) {
            $model->attributes = Yii::app()->request->getPost('Message');
            $model->repair_id = $id;
            $model->from_id = Yii::app()->user->id;
            if ($model->save()) {
                Yii::app()->user->setFlash('info', 'Your comment was added successfully');
                $this->redirect(Yii::app()->user->returnUrl);
                /** @var Repair $client */
                $client = Repair::model()->findByPk($id);
                $notif = new Message();

                if ($client->client_id == Yii::app()->user->id) {
                    $notif->from_id = Yii::app()->user->id;
                    $notif->to_id = Message::TO_ADMINS_AND_MODERS;
                } else {
                    $notif->from_id = Yii::app()->user->id;
                    $notif->to_id = $client->client_id;
                }

protected/views/crepair/_form.php
<?php
/* @var $this CrepairController */
/* @var $model Repair */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'repair-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?
	if($model->hasErrors()){
		foreach($model->errors as $r){
			echo $r[0].'<br/>';
		}
	}
	?>

	<div class="row">
		<?php echo $form->labelEx($model,'brand_id'); ?>
		<?php echo $form->textField($model,'brand_id'); ?>
		<?php echo $form->error($model,'brand_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'model'); ?>
		<?php echo $form->textField($model,'model',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'model'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'accessories'); ?>
		<?php echo $form->textField($model,'accessories',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'accessories'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'send_method'); ?>
		<?php echo $form->textField($model,'send_method'); ?>
		<?php echo $form->error($model,'send_method'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'old_service_pswd'); ?>
		<?php echo $form->textField($model,'old_service_pswd',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'old_service_pswd'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tracking_number'); ?>
		<?php echo $form->textField($model,'tracking_number',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'tracking_number'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'shiping_number'); ?>
		<?php echo $form->textField($model,'shiping_number',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'shiping_number'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'damage'); ?>
		<?php echo $form->textArea($model,'damage',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'damage'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'diagnostic'); ?>
		<?php echo $form->textArea($model,'diagnostic',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'diagnostic'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'client_id'); ?>
		<?php echo $form->textField($model,'client_id'); ?>
		<?php echo $form->error($model,'client_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'support_id'); ?>
		<?php echo $form->textField($model,'support_id'); ?>
		<?php echo $form->error($model,'support_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'warehouse_id'); ?>
		<?php echo $form->textField($model,'warehouse_id'); ?>
		<?php echo $form->error($model,'warehouse_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'price'); ?>
		<?php echo $form->textField($model,'price'); ?>
		<?php echo $form->error($model,'price'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/crepair/_search.php
<?php
/* @var $this UsersController */
/* @var $model User */
/* @var $form CActiveForm */
?>
<div class="wide form">
    <?php $form=$this->beginWidget('CActiveForm', array(
        'action'=>Yii::app()->createUrl($this->route),
        'method'=>'get',
    )); ?>
    <div class="col-lg-12" style="padding: 0px;">
        <?
        if(Yii::app()->controller->action->id == 'activeparts' || Yii::app()->controller->id == 'historyparts')
        {?>
        <div class="col-sm-6">
            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'accessories'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'accessories',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'repair_id'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'repair_id',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

        <div class="row"><div class="col-lg-5 input_label">
                <?php echo $form->labelEx($model,'damage'); ?>
            </div><div class="col-lg-7 input_container">
                <?php echo $form->textField($model,'damage',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
            </div></div>

        <div class="row"><div class="col-lg-5 input_label">
                <?php echo $form->labelEx($model,'diagnostic'); ?>
            </div><div class="col-lg-7 input_container">
                <?php echo $form->textField($model,'diagnostic',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
            </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'price'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->passwordField($model,'price',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

        <?
        }else{
        ?>
        <div class="col-sm-6">
            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'repair_id'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'repair_id',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'brand_id'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'brand_id',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'model'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'model',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'accessories'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'accessories',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'send_method'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'send_method',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'old_service_pswd'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'old_service_pswd',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'tracking_number'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'tracking_number',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'shiping_number'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'shiping_number',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'damage'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'damage',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>
        </div><div class="col-sm-6">
            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'diagnostic'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'diagnostic',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'client_id'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'client_id',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'support_id'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'support_id',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'status'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->textField($model,'status',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <div class="row"><div class="col-lg-5 input_label">
                    <?php echo $form->labelEx($model,'price'); ?>
                </div><div class="col-lg-7 input_container">
                    <?php echo $form->passwordField($model,'price',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
                </div></div>

            <?
            }
            $this->widget(
                'bootstrap.widgets.TbButton',
                array('buttonType' => 'submit',
                    'label' => 'Search',
                    'htmlOptions' => array('class' => 'repair_button'))
            );

            ?>
        </div></div>
    </div>
<?php $this->endWidget(); ?>

protected/views/crepair/index.php
<div class="col-lg-offset-2 col-sm-8">
	<div class="col-sm-12 reg_container" align="center">
		<div class="reg_header col-sm-12">
			<div class="col-sm-4">MANAGE REPAIRS</div>
			<div class="col-sm-5">
				<?
				$this->widget('bootstrap.widgets.TbButton', array(
					'label' => 'Active',
					'url' => Yii::app()->createAbsoluteUrl(Yii::app()->controller->id),
					'htmlOptions' => array('class' => 'menu_button')
				));
				$this->widget('bootstrap.widgets.TbButton', array(
					'label' => 'History',
					'url' => Yii::app()->createAbsoluteUrl(Yii::app()->controller->id . '/history'),
					'htmlOptions' => array('class' => 'menu_button')
				));
				$this->widget('bootstrap.widgets.TbButton', array(
					'label' => 'New Repair',
					'url' => Yii::app()->createAbsoluteUrl('repairs/new'),
					'htmlOptions' => array('class' => 'menu_button')
				));

				?>
			</div>
			<div class="col-sm-3" align="right">


				<div class="input-group">
					<?php echo CHtml::textField('inpSearch', '', array('class' => 'form-control', 'placeholder' => 'Serach...')); ?>
					<span class="input-group-addon">
<span class="glyphicon glyphicon-search"></span>
</span>
				</div>
			</div>
		</div>
		<?php
		/* @var $this CrepairController */
		/* @var $model Repair */

		$this->breadcrumbs = array(
			'Repairs' => array('index'),
			'Manage',
		);
		Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#repair-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
		?>

		<?php
		Yii::app()->clientScript->registerScript('search', "
  $('input#inpSearch').keyup(function(){
  $.fn.yiiGridView.update('repair-grid', {
  data: $(this).serialize()
  });
  return false;
});
");
		?>
		<div class="col-sm-12">

			<?php $this->widget('bootstrap.widgets.TbGridView', array(
				'id' => 'repair-grid',
				'type' => 'striped bordered condensed',
				'dataProvider' => $model->search(),
//	'filter'=>$model,
				'pager' => array(
					'cssFile' => 'style.css',
					'maxButtonCount' => '5',
					'header' => '', //'<b>Перейти к странице:</b><br><br>', // заголовок над листалкой
					'prevPageLabel' => 'Prev',
					'nextPageLabel' => 'Next',
					'htmlOptions' => array('class' => 'col-sm-12'),
					'selectedPageCssClass' => 'active'
				),
				'columns' => array(
					array(
						'name' => 'repair_id',
						'header' => 'ID',
						'value' => function ($data) {
								$d = explode('/', $data->date, 1);
								$t = $d[0];
								$r = $t[2] . $t[3];
								return '#' . $data->repair_id . '/' . $r;
							}
					),
					array(
						'name' => 'client_id',
						'header' => 'User Name',
						'value' => function ($data) {
								return $data->client->login;
							}
					),
					'date',
					array(
						'name' => 'support_id',
						'header' => 'Support',
						'value' => function ($data) {
								return (isset($data->support->login))?$data->support->login:"Not set yet";
							}
					),
					'diagnostic',
					array(
						'name' => 'status',
						'header' => '
                <div class="dropdown col-sm-12 dropdown_header">
    <a class="btn btn-default dropdown-toggle col-sm-12" data-toggle="dropdown" href="#">
        Status
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
                        <li
                        role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=0">New order</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=1">Waiting
                         for Diagnostic</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=2">Waiting for
                         customer agreement</a></li>

                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=3">Sent for repair</a></li>
                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=4">Waiting for spair parts</a></li>
                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=5">Spare parts derived</a></li>
                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=6">Successfully completed</a></li>
                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=7">Completed unsuccessfully</a></li>
                         <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]=8">Canceled by customer</a></li>

                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="?Repair[status]">All Repairs
                                                </a></li>
    </ul>
</div>
						',
						'htmlOptions' => array('style' => 'text-align:center;vertical-align: middle;'),
						'type' => 'html',
						'value' => function ($data) {
								$model = Colors::model()->getStatus($data->status);
								$a = '<div style="background-color:' . $model->color . ';">' . $model->description . '</div>';
								return $a;
							}
					),
					'price',
					array(
						'name' => 'repair_id',
						'header' => 'Actions',
						'type' => 'html',
						'value' => function ($data) {
								return '<a href="' . Yii::app()->createAbsoluteUrl('repairs/details/' . $data->repair_id) . '"><span class="glyphicon glyphicon-cog" style="padding: 5px"></span></a>';
							},

					),
				),
			)); ?>
		</div>
	</div>
</div>